### ISSUE TITLE
Depict the output in json format

### ISSUE THREAD

**Issue by Abhinav-26** [devtron-labs/silver-surfer#11]
Introduce the capability in silver-surfer (kubedd) command to show the output in json format,  using this flag  `-o json`.

for eg. - `./kubedd -o json` this command should give the output in json format

**Comment by fumblehool** [comment]
Hi @Abhinav-26, I would like to work on this.
Can you please assign me this task?

**Comment by Abhinav-26** [comment]
> Hi @Abhinav-26, I would like to work on this. Can you please assign me this task?

Yeah, sure.
I have assigned this issue to you.

**Comment by Moumoutaru** [comment]
Has there been any traction on this @fumblehool? This is a much needed project but the current output is not the most ideal way to consume it.

**Comment by Abhinav-26** [comment]
Hii @fumblehool, are you still interested in working on this?

**Comment by Abhinav-26** [comment]
> 

Hii @Moumoutaru, would you be interested in taking this issue? 
Looks like @fumblehool has not been active lately.

**Comment by pghildiyal** [comment]
merged in mail
