### ISSUE TITLE
Can we still use kubedd for AKS 1.29v upgrade?

### ISSUE THREAD

**Issue by ragurajendran86** [devtron-labs/silver-surfer#41]
we were using this tool for migrating from 1.25v to 1.27v. Now we are planning to migrate to 1.28 and then to 1.29v. I see this repo didnt have any commit recently and ReadMe still talk about 1.27v. 

Can we still use this for future upgrades?

**Comment by pghildiyal** [comment]
Yes you can use it for all future upgrades, 
kubedd doesnt store schema information in the cli, instead it fetches relevant open api spec from the github repository of kubernetes and therefore can validate migration against any kubernetes version.
