### ISSUE TITLE
Q: How to see all issues?

### ISSUE THREAD

**Issue by wrdls** [devtron-labs/silver-surfer#6]
How can I see which 4 issues I have to fix for the following result?

```shell
>>>> Newer Versions available <<<<
 Namespace         Name                                         Kind           API Version (Current Available)   Replace With API Version (Latest Available)   Migration Status                                   
 my-namespace   my-ingress                                 Ingress        networking.k8s.io/v1beta1         networking.k8s.io/v1                          4 issue(s): fix issues before migration
```

If it's too much to print detailed output in this tabular form, maybe we can have a different output format (e.g. json)?

**Comment by pghildiyal** [comment]
@wrdls issues are present in the table below this table, currently json output is not supported though data is already in a format so that it can be printed in json easily. I will try to pick it up if you would have bandwidth then can you pick it up?

Thanks

**Comment by wrdls** [comment]
Oh, I see. Not sure why I missed that those two tables are related.

About JSON output, I wouldn't mind getting involved but I'm not sure when I'd be able to work on this.
